int Start(int n, int arr[]);
void Menu();
void subMenu1();
void subMenu2();
int ShowArr(int n, int arr[]);
int ShowArrColumn(int n, int arr[]);
int SortUp(int n, int arr[]);
int SortDown(int n, int arr[]);
int WhoMany(int n, int arr[]);
int Sum(int n, int arr[]);
int Swap(int n, int arr[]);
int Split(int n, int arr[]);
int Zip(int n, int arr[]);